default:

  # directory_file_server                               : "//fileshare/agrus"
  # directory_output                                    : !expr strftime(Sys.time(), "{directory_file_server}/data-private/derived/%Y-%m-%d")

  # path_log_flow                                       : !expr strftime(Sys.time(), "data-unshared/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")
  # path_log_flow                                       : !expr strftime(Sys.time(), "//fileshare/agrus/log/%Y/%Y-%m/flow-%Y-%m-%d--%H-%M-%S.log")

  path_raw_sunrise                                    : "data-public/raw/date-sunrise-2022.csv"
  path_derived_sunrise_csv                            : "data-public/derived/date-sunrise-2022.csv"
  path_derived_sunrise_rds                            : "data-public/derived/date-sunrise-2022.rds"
  # path_metadata_ss_dx                                 : "data-public/metadata/ss-dx.csv"

  month_02:   "Лютий 2022"
  month_03:   " Березень"
  month_04:   " Квітень"
  day_of_invasion: "Доба після другого вторгнення"
  number_symbol: "№"
  day_ua: "день"
  date_ua: "дата"
  sirens_per_day: "Кількість повітряних тривог за добу"
  zenith_ua: " зеніт"
  dusk_astro_ua: "астрономічнi"
  dusk_nautical_ua: "морськi"
  dusk_civil_ua:  "цивільнi сутінки"

  dawn_civil_ua:  "цивільний світанок"
  dawn_nautical_ua: "морський"
  dawn_astro_ua: "астрономічний"

  monday_ua: "Пт"
  tuesday_ua: "Сб"
  wednesday_ua: "Нд"
  thursday_ua: "Пн"
  friday_ua: "Вт"
  saturday_ua: "Ср"
  sunday_ua: "Чт"

  title_ua: "Тривалисть та частота повітряних тривог у м.Вінниця"
  subtitle_ua: "м.Вінниця, перший місяць війни 2022 року"
  caption_ua: "Design by Will Beasley and Andriy Koval, data by Victor Dyadkovych                                                                      "
  y_label_ua: "Година доби"

  # time_zone_local               :  "America/Chicago"          # Force time calculations to be local, in case remotely run.
